# Generated by Django 5.1.7 on 2025-03-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_hours', models.FloatField(default=0)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('duty_status', models.CharField(choices=[('OD', 'Off Duty'), ('SB', 'Sleeper Berth'), ('DR', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=2)),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='trucker_logbook.trip')),
            ],
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_miles_driving', models.FloatField(default=0)),
                ('total_off_duty_hours', models.FloatField(default=0)),
                ('total_sleeper_berth_hours', models.FloatField(default=0)),
                ('total_driving_hours', models.FloatField(default=0)),
                ('total_on_duty_hours', models.FloatField(default=0)),
                ('total_lines_3_4', models.FloatField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucker_logbook.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_stop_frequency', models.FloatField(default=1000)),
                ('pickup_dropoff_time', models.FloatField(default=1)),
                ('minimum_rest_stop', models.FloatField(default=0.5)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucker_logbook.trip')),
            ],
        ),
    ]
